services:
  wol-api:
    image: ghcr.io/bramsuurdje/wol-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=
      - MAC_ADDRESS=
      - IP_ADDRESS=
    restart: unless-stopped
    networks:
      - wol-network

networks:
  wol-network:
    driver: bridge
